Billing beautify payment method modal
sap-labs-france/ev-dashboard pull request #2336
Opened 2021-04-02 09:58 UTC by cabch

- added stripe text
- added checkbox for bank details reuse

- changed modal ui
- reorganized folders to separate global payment stuff from stripe specific
- added locale error messages
- handled save + exit button to avoid multiple clicking

2021-04-07 15:31 UTC, ClaudeROSSI requested changes
3 minor issues to fix!

2021-04-07 15:31 UTC, ClaudeROSSI commented on src/assets/i18n/fr.json
> +      "payment_methods_check": "J'ai lu les conditions générales d'utilisation et j'accepte que mes informations de paiement soit utilisées pour payer mes futures sessions de recharge.",
soit ==> soient!

2021-04-07 15:31 UTC, ClaudeROSSI commented on src/assets/i18n/fr.json
> +      "payment_methods_conditions": "Pour des raisons de sécurité, nous ne stockons ni ne traitons vos informations de moyen de paiement. Les informations collectées sont envoyées de manière sécurisé
fourni ==> fournit

2021-04-07 15:31 UTC, ClaudeROSSI commented on src/assets/scss/material-dashboard.scss
> +@import "views/billing/\ billing.scss";
c'est normal le /\ ???

2021-04-07 15:31 UTC, ClaudeROSSI commented on src/assets/scss/views/billing/ billing.scss
> +}
file name starts with a space!!!! ????

2021-04-08 07:32 UTC, cabch commented on src/assets/scss/material-dashboard.scss
> +@import "views/billing/\ billing.scss";
non c'était à cause de l'espace du nom du fichier. Done ✅

2021-04-08 07:32 UTC, cabch commented on src/assets/scss/views/billing/ billing.scss
> +}
oups
changed ✅

2021-04-08 07:32 UTC, cabch commented on src/assets/i18n/fr.json
> +      "payment_methods_conditions": "Pour des raisons de sécurité, nous ne stockons ni ne traitons vos informations de moyen de paiement. Les informations collectées sont envoyées de manière sécurisé
done ✅

2021-04-08 07:33 UTC, cabch commented on src/assets/i18n/fr.json
> +      "payment_methods_check": "J'ai lu les conditions générales d'utilisation et j'accepte que mes informations de paiement soit utilisées pour payer mes futures sessions de recharge.",
done ✅

2021-04-08 07:44 UTC, ClaudeROSSI approved these changes
ok

2021-04-08 20:27 UTC, merged