Display save button on companies, add canCreate flag to companies/sites/site areas
sap-labs-france/ev-dashboard pull request #2344
Opened 2021-04-07 16:56 UTC by Fonsu

* Temporarily display 'save' button to fix bug
* Need to further discuss about the way to fetch/set `canCreate`

2021-04-07 20:04 UTC, jerome-benoit commented
> * Temporarily display 'save' button to fix bug

I think by scratching your head a bit more, you can find a proper fix: 
`*ngIf="canUpdateCompany"` miss a condition to handle the update authorization, the proper fix is to find the right one.

2021-04-07 23:58 UTC, LucasBrazi06 commented
@Fonsu As discussed via email, pass the available canCreate, canUpdate that you have in the list to the pop-up and use them.

2021-04-08 22:14 UTC, LucasBrazi06 commented
@Fonsu Any news on this one?

2021-04-09 08:54 UTC, Fonsu commented
> @Fonsu Any news on this one?

I'm done with companies, can you take a look? At the moment I'm also replicating these changes to Sites and Site Areas, need to check if this approach will cover all other use cases. 

`createWithAuthorizations` is a temporary method to avoid changing 10+ create actions with potential regressions but my idea would be to remove the original `create` method eventually, once all use cases are covered and double checked.

2021-04-09 09:46 UTC, LucasBrazi06 commented
> > @Fonsu Any news on this one?
> 
> I'm done with companies, can you take a look? At the moment I'm also replicating these changes to Sites and Site Areas, need to check if this approach will cover all other use cases.
> 
> `createWithAuthorizations` is a temporary method to avoid changing 10+ create actions with potential regressions but my idea would be to remove the original `create` method eventually, once all use cases are covered and double checked.

If you want me to take a look, move your issue to To be reviewed ;-)

2021-04-09 12:49 UTC, LucasBrazi06 requested changes
Good approach for canCreate.
I would use also the same approach with canUpdate,
Check my comments.

2021-04-09 12:49 UTC, LucasBrazi06 commented on src/app/pages/organization/companies/company/company.dialog.component.ts
> +    if(typeof data === 'boolean'){
You should pass both canCreate and canUpdate in the data.
Make data a Json document which contains both flags + the companyID.

2021-04-09 12:49 UTC, LucasBrazi06 commented on src/app/pages/organization/companies/company/company.component.ts
> +  @Input() public canCreateCompany: boolean;
Pass also canUpdateCompany.
No need to get it from the company in the HTTP request now.

2021-04-09 12:49 UTC, LucasBrazi06 commented on src/app/pages/organization/companies/list/companies-list-table-data-source.ts
> +            canCreate: this.canCreateCompany
Add also canUpdate.

2021-04-09 21:27 UTC, merged

2021-04-09 21:28 UTC, LucasBrazi06 commented
@Fonsu I finally merged it to have a better readability on the next changes.
I tested it and I didn't find any showstopper.
Other devs will also test their code with these changes