Authorizations > Front-end: Enhancement of the current concept (Sites)
sap-labs-france/ev-dashboard pull request #2369
Opened 2021-04-19 16:15 UTC by Fonsu

2021-04-19 22:14 UTC, LucasBrazi06 requested changes
I think we can pass the whole Site object to both pop-ups and if tomorrow we add new props, we'll benefit from getting them right from the object without changing anything in the dialog data / template.
Let me know if this is clear.
If not I can try to make a PR on top of yours to check if it's feasible.
If yes, you can have a look and merge it to yours and then I'll merge both the back and the front PRs together.

2021-04-19 22:14 UTC, LucasBrazi06 commented on src/app/pages/organization/sites/site/site-dialog.component.ts
> +  template: '<app-site #appRef [currentSiteID]="siteID" [canUpdateSite]="canUpdateSite" [inDialog]="true" [dialogRef]="dialogRef"></app-site>',
Should we pass the site so if we enrich again the object, we will have new props for free without touching template.

2021-04-19 22:14 UTC, LucasBrazi06 commented on src/app/shared/table/actions/sites/table-assign-users-to-site-action.ts
> +    data: SiteDialogData, refresh?: () => Observable<void>) => void;
site: Site?

2021-04-19 22:14 UTC, LucasBrazi06 commented on src/app/types/Authorization.ts
> +export interface SiteDialogData extends DialogData, SiteAuthorizationActions {
Maybe not needed

2021-04-19 22:14 UTC, LucasBrazi06 commented on src/app/types/Table.ts
> +export interface SiteData extends Data, SiteAuthorizationActions {
We can keep only data as mother class of Site

2021-04-19 22:14 UTC, LucasBrazi06 commented on src/app/types/Site.ts
> +export interface SiteUser extends SiteData {
We can keep data here I think. We can down/upcast the type in the code I think.

2021-04-19 22:14 UTC, LucasBrazi06 commented on src/app/types/Site.ts
> +export interface Site extends SiteData, CreatedUpdatedProps {
We can keep data here I think. We can down/upcast the type in the code I think.

2021-04-20 07:38 UTC, LucasBrazi06 commented
@Fonsu What about another solution to have a pop-up mode property with enums read, update and create to display the Site or Company pop-ups.
And for the other kind of pop-up like Assign Users we can pass the whole Site object where we can directly read values.
What do you think?

2021-04-20 12:29 UTC, Fonsu commented
Thank you for your review 🙂 

> I think we can pass the whole Site object to both pop-ups and if tomorrow we add new props, we'll benefit from getting them right from the object without changing anything in the dialog data / template.

That makes sense, that way we don't strip the `site.id` from `site` and pass it to the popup only to fetch the whole site from the backend again. Done in my last two commits. 

> @Fonsu What about another solution to have a pop-up mode property with enums read, update and create to display the Site or Company pop-ups.
> And for the other kind of pop-up like Assign Users we can pass the whole Site object where we can directly read values.
> What do you think?

Maybe 'enriching' `site` in `sites-list-table-data-source.ts:220` so that there is also a `mode` that can be checked on `site.component.html` would be useful. I am not entirely sure if that is what you mean, though. With this approach there would be no need to 'force' `canUpdate` to `false` in the view action, which would definitely improve readability.

2021-04-20 13:11 UTC, LucasBrazi06 commented
> That makes sense, that way we don't strip the `site.id` from `site` and pass it to the popup only to fetch the whole site from the backend again. Done in my last two commits.

Thanks!

> Maybe 'enriching' `site` in `sites-list-table-data-source.ts:220` so that there is also a `mode` that can be checked on `site.component.html` would be useful. I am not entirely sure if that is what you mean, though. With this approach there would be no need to 'force' `canUpdate` to `false` in the view action, which would definitely improve readability.

You can check this when the action is triggered and set the PopupMode when calling it.
If it's ok for you, you can go ahead.

2021-04-22 13:43 UTC, merged