secure ui when activating billing of transactions
sap-labs-france/ev-dashboard pull request #2423
Opened 2021-05-28 15:06 UTC by cabch

2021-05-30 21:09 UTC, ClaudeROSSI requested changes
small side effect on the position of the url (to stripe).
Can you change it? 

I pushed some changes to replace the term "transactions" by the term "charging sessions"

2021-05-30 21:09 UTC, ClaudeROSSI commented on src/app/pages/settings-integration/billing/stripe/settings-stripe.component.html
> +      <div *ngIf="transactionBillingActivated" class="col-md-6 deactivated-setting-message">
This has a side effect on the position of the first the url. Can you change it?

![image](https://user-images.githubusercontent.com/26900551/120120024-2f255700-c19b-11eb-98e3-36f42b7396f2.png)

2021-05-30 21:09 UTC, ClaudeROSSI commented on src/assets/i18n/de.json
> +      "deactivated_setting_message": "Billing of transactions is activated, you cannot change the billing information anymore",
the term transaction is confusing (and only used internally). The UI always uses the term "sessions" (or charging sessions).

I'll make a proposal with different terms.

2021-05-31 09:15 UTC, cabch commented on src/app/pages/settings-integration/billing/stripe/settings-stripe.component.html
> +      <div *ngIf="transactionBillingActivated" class="col-md-6 deactivated-setting-message">
done ✅

2021-05-31 09:15 UTC, cabch commented on src/assets/i18n/de.json
> +      "deactivated_setting_message": "Billing of transactions is activated, you cannot change the billing information anymore",
ok 👍🏻

2021-05-31 09:39 UTC, ClaudeROSSI approved these changes

2021-05-31 09:43 UTC, merged