disabled button when error at start transaction
sap-labs-france/ev-dashboard pull request #2472
Opened 2021-06-23 14:09 UTC by cabch

added
- disabled button when error at start transaction
- i18n for error messages

+ deleted bold text in billing setting

2021-06-23 14:53 UTC, ClaudeROSSI commented on src/app/pages/charging-stations/charging-station-start-transaction/charging-stations-start-transaction-dialog-component.ts
> +  public errors: string;
errors ==> confusing
errorDescription?

2021-06-23 14:53 UTC, ClaudeROSSI requested changes
almost ok

2021-06-23 16:24 UTC, ClaudeROSSI approved these changes

2021-06-23 16:24 UTC, merged

2021-06-24 12:32 UTC, cabch commented on src/app/pages/charging-stations/charging-station-start-transaction/charging-stations-start-transaction-dialog-component.ts
> +  public errors: string;
modified ✅