Csv import siteIDs front
sap-labs-france/ev-dashboard pull request #2473
Opened 2021-06-25 13:25 UTC by cabch

- added isImported to know where the user come from -> used in back
- added 'auto activation at import' to headers to send to BE + checkbox
- added siteIDs to optional properties in modal
- i18n messages to match Y/N dialog message

2021-07-05 12:52 UTC, ClaudeROSSI approved these changes
no comments from my side

2021-07-22 17:27 UTC, LucasBrazi06 requested changes
I think we should add user's fields as optional fields in import Tags pop-up:

![2021-07-22_19-26-09](https://user-images.githubusercontent.com/25266945/126682536-25a2e685-578d-4ae9-95b8-115b0b9d2acd.png)

2021-07-23 14:03 UTC, cabch commented
import tag pop up optionnal fields modified 👌🏻

2021-07-28 14:14 UTC, LucasBrazi06 approved these changes

2021-07-28 14:15 UTC, merged