Display warning if public charging stations exist under site about to be made private
sap-labs-france/ev-dashboard pull request #2543
Opened 2021-09-02 11:52 UTC by RohanAntony

2021-09-02 12:01 UTC, RohanAntony commented
@LucasBrazi06 If a charging station is made public when the site is private, an error is thrown by the backend but not being handled in the front-end yet. Raising an [issue](https://github.com/sap-labs-france/ev-dashboard/issues/2544).

2021-09-02 20:28 UTC, LucasBrazi06 requested changes
Also check public Charging Station on non public Site

2021-09-02 20:28 UTC, LucasBrazi06 commented on src/app/pages/organization/sites/site/site.component.ts
> +        case HTTPError.SITE_WITH_PUBLIC_CHARGER_ERROR:
Only one name for Charging Station, we avoid now CHARGER or ChargeBox...

2021-09-07 06:37 UTC, LucasBrazi06 approved these changes

2021-09-07 06:37 UTC, merged