Tag tab ,basic user manage his own badges , user not mandatory in badges anymore
sap-labs-france/ev-dashboard pull request #2553
Opened 2021-09-07 16:38 UTC by mahdibenromdhane

2021-09-08 16:14 UTC, LucasBrazi06 commented
@mahdibenromdhane Why the name of your branch is daf28b1 !? :-)

2021-09-08 16:22 UTC, mahdibenromdhane commented
> @mahdibenromdhane Why the name of your branch is [daf28b1](https://github.com/sap-labs-france/ev-dashboard/commit/daf28b15a6ec5093dc80bf6b8dfdd52e0db34f39) !? :-)
I Had the same problem with git push that we faced yesterday in the server, so I generated a branch from a previous commit and the branch took the commit id as a name

2021-09-08 16:41 UTC, LucasBrazi06 reviewed
Just small comments.
I'll test the UI now.

2021-09-08 16:41 UTC, LucasBrazi06 commented on src/app/pages/transactions/history/transactions-history-table-data-source.ts
> +    const visualTagID = this.windowService.getSearch('VisualTagID');
VisualTagID -> VisualID ?

2021-09-08 17:02 UTC, LucasBrazi06 requested changes
- What happens if an active unassigned badge is used to start a transaction?
- If not Assigned to a User you cannot set the Default flag (UI + backend) -> Force default to false
- For Basic user rename the Assign/Unassign (only i18n):
    - Assign -> Register
    - Unassign -> Delete
- Unassign in table row -> Use the same icon and color as in the toolbar button
- When basic user 'deletes' the tag, it should be marked as inactive
- Basic user cannot assign an inactive badge to himself
- He cannot change the status of the badge either

2021-09-09 17:33 UTC, mahdibenromdhane commented
> * What happens if an active unassigned badge is used to start a transaction?
> * If not Assigned to a User you cannot set the Default flag (UI + backend) -> Force default to false
> * For Basic user rename the Assign/Unassign (only i18n):
>   
>   * Assign -> Register
>   * Unassign -> Delete
> * Unassign in table row -> Use the same icon and color as in the toolbar button
> * When basic user 'deletes' the tag, it should be marked as inactive
> * Basic user cannot assign an inactive badge to himself
> * He cannot change the status of the badge either

- an error occur if an active unassigned badge is used to start a transaction
- ![image](https://user-images.githubusercontent.com/33232018/132733959-455d4df0-ecc2-488c-8e8e-e27f0dc2e848.png)
- Done for the rest of remarks

2021-09-14 15:25 UTC, mahdibenromdhane commented on src/app/pages/tags/tag-assign/tag-assign.component.ts
> -    if (!this.canListUsers) {
Removed because siteOwner can list users but cannot assign/create badge for other users in authorizationsDefinition

2021-09-23 07:33 UTC, LucasBrazi06 approved these changes
I approve but change the following:
- UserID is mandatory for Site Admin when creating a Badge

2021-09-23 07:33 UTC, merged