Tariff id in site area
sap-labs-france/ev-dashboard pull request #2717
Opened 2021-11-02 17:20 UTC by rmangin-fr

2021-11-16 16:17 UTC, ClaudeROSSI approved these changes
ok

2021-12-22 11:01 UTC, ClaudeROSSI requested changes
please heck my comment

2021-12-22 11:01 UTC, ClaudeROSSI commented on src/app/pages/organization/site-areas/site-area/site-area.component.html
> +      </mat-tab>
As far as I understood, Serge would like to split this in two components (one component per tabs).
Something similar to what has been done for sites (with site/main & site/site-ocpi).
@OliveGerste : did you discuss that point with Remi?

![image](https://user-images.githubusercontent.com/26900551/147082454-07ab692c-19c5-491d-b11e-c94ade32b780.png)

2021-12-22 13:07 UTC, ClaudeROSSI requested changes
Serge wants a component per tabs!

2021-12-23 09:34 UTC, OliveGerste commented on src/app/pages/organization/site-areas/site-area/site-area.component.html
> +      </mat-tab>
I thought about this as well, but then it seemed more like a refactoring to me. 
@LucasBrazi06 Should this be done in this PR or do we create a separate issue for this?

2022-01-03 09:23 UTC, LucasBrazi06 commented on src/app/pages/organization/site-areas/site-area/site-area.component.html
> +      </mat-tab>
> I thought about this as well, but then it seemed more like a refactoring to me. @LucasBrazi06 Should this be done in this PR or do we create a separate issue for this?

To be done in this PR.
Thanks!

2022-01-03 14:34 UTC, LucasBrazi06 commented
@OliveGerste As replied earlier, split the view.
Thanks!

2022-01-06 14:00 UTC, OliveGerste commented
> @OliveGerste As replied earlier, split the view. Thanks!

All right. Should I only add the ne component as a new view or do you want me to also split the old component into main and tab component.

2022-01-06 17:43 UTC, LucasBrazi06 commented
> > @OliveGerste As replied earlier, split the view. Thanks!
> 
> All right. Should I only add the new component as a new view or do you want me to also split the old component into main and tab component like it is done in site already?

Like the Site, thanks!!!

2022-01-18 16:48 UTC, LucasBrazi06 approved these changes

2022-01-18 16:48 UTC, merged