Sub site area enablement
sap-labs-france/ev-dashboard pull request #2744
Opened 2021-11-16 09:26 UTC by OliveGerste

2021-11-24 07:58 UTC, LucasBrazi06 commented
@ClaudeROSSI Could you have a look at this one after the pricing?
Thanks!

2021-11-24 19:18 UTC, ClaudeROSSI requested changes
As a general remark I do not like the fact that "parent" is a suffix (and not a prefix) of most of the variables, constants and texts!

Please check my comments and let me know what you think!

2021-11-24 19:18 UTC, ClaudeROSSI commented on src/app/types/HTTPError.ts
> +  SITE_AREA_PARENT_ERROR = 541,
Form my perspective, this HTTP error is a bit too generic.

I think it would make sense to distinguish between the various errors that we may have:
- SITE_AREA_CIRCULAR_STRUCTURE_ERROR
- SITE_AREA_STRUCTURE_INCONSISTENCY_ERROR
- SITE_AREA_DEPENDENCY_ERROR (can't delete since it has child site areas)

2021-11-24 19:18 UTC, ClaudeROSSI commented on src/assets/i18n/en.json
> +    "site_area_parent": "Site Area Parent",
Parent Site Area
do you agree?

2021-11-24 19:18 UTC, ClaudeROSSI commented on src/assets/i18n/en.json
> +    "site_area_parent_error_title": "Sub Site Area Error",
Site Area Hierarchy Error??

2021-11-24 19:18 UTC, ClaudeROSSI commented on src/assets/i18n/en.json
> +    "site_area_parent_error_body": "An error occurred while updating the site area chain. Please make sure that there are no circular structures and that all sub site areas and its parents have the s
as already mentioned ... I would expect too different messages.
Let me know if this makes sense

2021-11-24 19:18 UTC, ClaudeROSSI commented on src/app/types/SiteArea.ts
> +  siteAreaParentID?: string;
idem
parentSiteArea
parentSiteAreaID

2021-11-25 16:20 UTC, OliveGerste commented
> As a general remark I do not like the fact that "parent" is a suffix (and not a prefix) of most of the variables, constants and texts!
> 
> Please check my comments and let me know what you think!

Hi Claude, 

Thanks a lot for the initial review. I completely agree with your comments. 
I made the necessary changes in front end and back end.

2021-11-26 14:24 UTC, ClaudeROSSI requested changes
wrong i18n key ... check my comments

2021-12-22 13:44 UTC, ClaudeROSSI requested changes
small mistake in i18n key

2021-12-22 13:44 UTC, ClaudeROSSI commented on src/app/pages/organization/site-areas/site-area/site-area.component.ts
> +          this.messageService.showErrorMessage('site_areas.site_areas_do_not_exist');
wrong i18n key

site_areas_do_not_exist
site_area_do_not_exist

??? site_area_does_not_exist ???

2021-12-23 08:42 UTC, OliveGerste commented on src/app/pages/organization/site-areas/site-area/site-area.component.ts
> +          this.messageService.showErrorMessage('site_areas.site_areas_do_not_exist');
I reused a wrong key and made a spelling mistake in advance. :D 
Fixed

2021-12-27 13:15 UTC, ClaudeROSSI approved these changes
approved.

I've change the french texts!

2022-03-09 10:15 UTC, LucasBrazi06 approved these changes

2022-04-25 15:35 UTC, LucasBrazi06 commented
> @LucasBrazi06 : I cannot create a site area anymore.
> The save button remains disabled

Have you checked the limit tab ?

2022-04-25 15:38 UTC, ClaudeROSSI commented
I know

I’m just a normal user lol

De : FABIANO Serge ***@***.***>
Date : lundi, 25 avril 2022 à 17:37
À : sap-labs-france/ev-dashboard ***@***.***>
Cc : ROSSI, Claude ***@***.***>, Mention ***@***.***>
Objet : Re: [sap-labs-france/ev-dashboard] Sub site area enablement (PR #2744)

@LucasBrazi06<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLucasBrazi06&data=05%7C01%7Cclaude.rossi%40sap.com%7C080d2e978f9247fa2d3608da26d17d1b%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C637864978427554525%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RaMf%2BbLd%2Fd050yKVq7UyThwlflFNC0h1QlWWCk9sDJM%3D&reserved=0> : I cannot create a site area anymore.
The save button remains disabled

Have you checked the limit tab ?

right ... that's the pb ... but it was not red :)

We discussed this issue together already :-)

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsap-labs-france%2Fev-dashboard%2Fpull%2F2744%23issuecomment-1108733535&data=05%7C01%7Cclaude.rossi%40sap.com%7C080d2e978f9247fa2d3608da26d17d1b%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C637864978427554525%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Q7OqsnA0DFJmQrLWzluwia%2FxHJ3u%2FWMZFfWzbCSXNLM%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGNHQR5ZLTLAH2YZFI3WRWLVG233BANCNFSM5IDYK3JA&data=05%7C01%7Cclaude.rossi%40sap.com%7C080d2e978f9247fa2d3608da26d17d1b%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C637864978427554525%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=v%2BtYed8YCFEY602gbhcaT8eIbHmLkQsVWBnTopCebvw%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-04-29 07:03 UTC, ClaudeROSSI reviewed
some i18n comments

2022-04-29 07:03 UTC, ClaudeROSSI commented on src/assets/i18n/en.json
> +      "2 - Attach all children to the parent Site Area",
suggestion:

> 2 - Assign the current parent site area to all children

2022-04-29 08:06 UTC, LucasBrazi06 commented on src/assets/i18n/fr.json
> +      "2 - Rattacher les sous-zones a la zone parente",
Ok, done

2022-04-29 08:06 UTC, LucasBrazi06 commented on src/assets/i18n/fr.json
> +      "La Zone doit avoir la même valeure Charge Intelligente que son parent."
Done

2022-04-29 08:10 UTC, LucasBrazi06 commented on src/assets/i18n/en.json
> +      "2 - Attach all children to the parent Site Area",
Done

2022-05-17 19:56 UTC, merged