Quick option to set a commonly used date range in to and from field.
sap-labs-france/ev-dashboard pull request #2894
Opened 2022-01-05 09:14 UTC by RohanAntony

Added an option in filter that looks like a calendar with event marked on it.
![image](https://user-images.githubusercontent.com/5779016/148191688-f49720ae-601f-4819-a45d-788d1bcf5ae4.png)

When selecting this week
![image](https://user-images.githubusercontent.com/5779016/148191807-e77944e6-2879-4e64-9838-27ec46343a7e.png)

2022-01-05 14:07 UTC, LucasBrazi06 commented
@RohanAntony Quick feedback.
I would have put the selection after the date filters and choose an icon like a stop watch to not confuse it with the ones in the filters.
Thanks!

2022-01-05 14:18 UTC, RohanAntony commented
> @RohanAntony Quick feedback. I would have put the selection after the date filters and choose an icon like a stop watch to not confuse it with the ones in the filters. Thanks!

![image](https://user-images.githubusercontent.com/5779016/148232393-9e0c33cf-8861-48c8-a8d2-3c40a1908fe7.png)

2022-01-05 14:22 UTC, LucasBrazi06 commented
> ![image](https://user-images.githubusercontent.com/5779016/148232393-9e0c33cf-8861-48c8-a8d2-3c40a1908fe7.png)

In white theme :-) and is there a way to display it in a button?

2022-01-05 14:32 UTC, RohanAntony commented
> > ![image](https://user-images.githubusercontent.com/5779016/148232393-9e0c33cf-8861-48c8-a8d2-3c40a1908fe7.png)
> 
> In white theme :-) and is there a way to display it in a button?

![image](https://user-images.githubusercontent.com/5779016/148234664-09d8f3b8-8dfc-4baf-beb8-a613da462c98.png)

2022-01-05 15:47 UTC, LucasBrazi06 requested changes
Check my comments

2022-01-05 15:47 UTC, LucasBrazi06 commented on src/app/shared/table/table.component.ts
> +    if(filterDef.id === 'date_menu_dropdown') {
This code should not be there.
The two date filters should be passed to the DateMenuDropdownFilter object which will update the Json date objects according the drop down selection.
The this code should be in the DateMenuDropdownFilter.
I don't know if the framework is supporting that currently.
You can check with Mahdi who did the dependencies between filters.

2022-01-05 15:47 UTC, LucasBrazi06 commented on src/app/shared/table/table.component.html
> +              <button mat-stroked-button [matMenuTriggerFor]="menu">
Use the primary (blue) button design (same as the ones in the toolbar)

2022-01-05 15:47 UTC, LucasBrazi06 commented on src/app/shared/table/table.component.html
> +              <button mat-stroked-button [matMenuTriggerFor]="menu">
If it's possible also, reduce the width of the button so we have a square button and not a rectangular one.

2022-01-17 21:55 UTC, RohanAntony commented
Closing PR as [Date Range Picker PR](https://github.com/sap-labs-france/ev-dashboard/pull/2895) replaces this.

2022-01-17 21:55 UTC, closed without merging