Split pricing dialog
sap-labs-france/ev-dashboard pull request #3005
Opened 2022-02-24 10:43 UTC by cabch

needed to make the dialog refactoring correctly - less impact doing it this way than doing dialog refactoring before pricing split

2022-02-25 16:42 UTC, ClaudeROSSI requested changes
a few unexpected behaviors when editing.

2022-02-25 16:42 UTC, ClaudeROSSI commented on src/app/shared/pricing-definitions/pricing-definition/restrictions/pricing-definition-restrictions.component.ts
> +      this[event.source.id].setValidators(Validators.compose([
idem ... not called when editing

2022-02-25 16:42 UTC, ClaudeROSSI commented on src/app/shared/pricing-definitions/pricing-definition/restrictions/pricing-definition-restrictions.component.ts
> +export class PricingDefinitionRestricitionsComponent implements OnInit, OnChanges {
typo - class name is wrong "restric**i**tions"

![image](https://user-images.githubusercontent.com/26900551/155752232-62f9029a-f704-43fb-9d76-7d8c7f70a6e7.png)

2022-02-25 16:42 UTC, ClaudeROSSI commented on src/app/utils/PricingHelpers.ts
> +      if (!Utils.isNullOrUndefined(fieldMinValue) && !Utils.isNullOrUndefined(fieldMaxValue) && fieldMaxValue !== '' && fieldMinValue !== '' && fieldMinValue >= 0 && fieldMaxValue >= 0) {
??? why do we check for empty strings? 
??? fieldMinValue !== '' - I do not understand!

2022-02-25 16:42 UTC, ClaudeROSSI commented on src/app/shared/pricing-definitions/pricing-definition/restrictions/pricing-definition-restrictions.component.ts
> +      this.clearAndResetControl(this.timeTo);
Not called when editing a pricing definition where the restrictions are already set.

Should be called explicitly when openning the dialog!

2022-03-02 08:55 UTC, cabch commented on src/app/utils/PricingHelpers.ts
> +      if (!Utils.isNullOrUndefined(fieldMinValue) && !Utils.isNullOrUndefined(fieldMaxValue) && fieldMaxValue !== '' && fieldMinValue !== '' && fieldMinValue >= 0 && fieldMaxValue >= 0) {
if field has been erased but still toggled on we have an empty string so it passes the if condition and goes to the Number('emptystring') that resolves to zero number whereas we should not have gone that far

![Screenshot 2022-03-02 at 09 50 50](https://user-images.githubusercontent.com/19712122/156327717-79dd206c-639c-4171-9ceb-b6a53fb204af.png)
g

2022-03-02 08:57 UTC, cabch commented on src/app/shared/pricing-definitions/pricing-definition/restrictions/pricing-definition-restrictions.component.ts
> +export class PricingDefinitionRestricitionsComponent implements OnInit, OnChanges {
oups
✅ modified in next commit

2022-03-07 20:10 UTC, ClaudeROSSI commented on src/app/utils/PricingHelpers.ts
> +      if (!Utils.isNullOrUndefined(fieldMinValue) && !Utils.isNullOrUndefined(fieldMaxValue) && fieldMaxValue !== '' && fieldMinValue !== '' && fieldMinValue >= 0 && fieldMaxValue >= 0) {
thanks for the changes

2022-03-09 14:41 UTC, ClaudeROSSI requested changes
as discussed on the phone ... check my comments

2022-03-09 14:41 UTC, ClaudeROSSI commented on src/app/shared/pricing-definitions/pricing-definition/pricing-definition.component.ts
> +      maxEnergyKWh: this.pricingDefinitionRestrictions.maxEnergyKWh.value || null,
@cabch : As discussed, please make sure to only save the value when the toggle is ON.

2022-03-09 15:57 UTC, ClaudeROSSI approved these changes
tested and approved.
Thanks

2022-03-09 15:59 UTC, ClaudeROSSI commented
@LucasBrazi06 : Everything is ok from my perspective.

2022-03-10 21:42 UTC, LucasBrazi06 approved these changes
Sounds good for me.
Feel free to change what I did after the merge.
Just one remark, if I create a pricing with only a name and a description, is it okay? Does it mean it's free?

2022-03-10 21:43 UTC, merged