Add mobile and phone number to register UI
sap-labs-france/ev-dashboard pull request #3037
Opened 2022-03-16 16:38 UTC by mahdibenromdhane

2022-03-28 13:09 UTC, LucasBrazi06 requested changes
Looks good, but I think only the Mobile phone is necessary.
You can also add a Required validator in the Mobile form control.

2022-03-30 13:14 UTC, LucasBrazi06 requested changes

2022-03-30 13:14 UTC, LucasBrazi06 commented on src/app/authentication/register/authentication-register.component.html
> +                        <mat-error *ngIf="mobile.errors?.invalidPhone">
Add generic message for required field!!!

2022-04-08 18:20 UTC, LucasBrazi06 commented
@mahdibenromdhane Have you checked with Alix to implement also this feature in the mobile app?
Otherwise you will block the register in the mobile app.
Mobile App must be deployed first.

2022-04-11 12:43 UTC, mahdibenromdhane commented
> @mahdibenromdhane Have you checked with Alix to implement also this feature in the mobile app? Otherwise you will block the register in the mobile app. Mobile App must be deployed first.

Yes ! Just checked with @AlixH, he will implement it on the mobile side.

2022-04-13 08:37 UTC, LucasBrazi06 approved these changes

2022-04-13 09:03 UTC, merged