display TENANT_DEFAULT_LOGO on superTenant
sap-labs-france/ev-dashboard pull request #3053
Opened 2022-03-30 13:41 UTC by mahdibenromdhane

2022-03-30 13:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sap-labs-france/ev-dashboard?pullRequest=3053) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/sap-labs-france/ev-dashboard?pullRequest=3053) before we can accept your contribution.<br/><hr/>**mahdibenromdhane** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sap-labs-france/ev-dashboard?pullRequest=3053) it.</sub>

2022-03-30 15:23 UTC, LucasBrazi06 requested changes
Check all the views in auth directory.
It's not only register and login I think.

2022-03-31 12:48 UTC, mahdibenromdhane commented
> Check all the views in auth directory. It's not only register and login I think.

Done

2022-04-04 08:11 UTC, LucasBrazi06 approved these changes
GUT Thanks !

2022-04-04 08:11 UTC, merged