Add navigate to transaction in chargingstation
sap-labs-france/ev-dashboard pull request #3372
Opened 2022-09-21 09:55 UTC by cabch

waiting for back to be merged so i can align the canListCompletedTransaction in backend

2022-09-23 07:42 UTC, ClaudeROSSI requested changes

2022-09-23 07:42 UTC, ClaudeROSSI commented on src/app/types/Authorization.ts
> +  canListCompletedTransactions?: boolean;
@cabch : c'est nouveau canListCompletedTransactions?
Je ne le vois pas server-side!

2022-09-26 09:49 UTC, cabch commented on src/app/types/Authorization.ts
> +  canListCompletedTransactions?: boolean;
oui c'est nouveau, j'attend que les authorizations server soient merged pour aligné car il y a des modifs server side que je dois uiliser.
Pour l'instant c'est en draft pour cette raison

2022-09-29 09:02 UTC, ClaudeROSSI approved these changes
ok

2022-09-29 09:02 UTC, merged