Show ocpi modal buttons on create mode
sap-labs-france/ev-dashboard pull request #3493
Opened 2023-01-09 22:41 UTC by mahdibenromdhane

2023-01-09 22:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sap-labs-france/ev-dashboard?pullRequest=3493) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/sap-labs-france/ev-dashboard?pullRequest=3493) before we can accept your contribution.<br/><hr/>**mahdibenromdhane** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sap-labs-france/ev-dashboard?pullRequest=3493) it.</sub>

2023-01-10 09:46 UTC, Ramzay requested changes
@mahdibenromdhane your modifications bypasses authorizations, which is not what we want, anyone could generate the token if it's empty... You should look at an object "DialogParamsWithAuth" to pass authorizations to a dialog.

@cabch will make the fix.

Thanks

2023-01-10 13:15 UTC, cabch commented
sounds ok for me now, added cans at page loading + pass them to the dialog + change the ngIf condition

2023-01-10 13:53 UTC, cabch commented
deleted old verification to "currentEndpoint" as the new cans are global
also updated imports

2023-01-10 15:32 UTC, Ramzay approved these changes

2023-01-10 15:32 UTC, merged